### ISSUE TITLE
Widget not using semantic.json labels for selector labels

### ISSUE THREAD

**Issue by dale42** [h5p/h5p-editor-radio-selector#1]
The Radio Selector widget is not using the "label" property from semantics.json to define the radio button labels. 

It uses a jquery selector: `var label = $(this).find('.h5peditor-label').eq(0).html();`

This makes a number of assumptions that are not true for every widget. It assumes that every component uses the `h5peditor-label` class for its label. It also assumes that a component will not update the value of the label. These assumptions are not true for the Group widget. It may not be true for others.

I've outlined this in the forum post: https://h5p.org/node/37027

As I explored the issue, I realized the answers I proposed in the post aren't the best ones. It would be best if the selector button labels are taken from the semantics.json definition.

I have a proposed code fix for using the semantics.json labels. I will attempt to submit a pull request if you are open to receiving it. I'm not quite sure what branch to submit it against.

**Comment by timothyylim** [comment]
Hi @dale42, thanks for the thorough investigation! You can submit a pull request against the master branch. The core team will be more than happy to take a look and try to integrate it.

**Comment by fnoks** [comment]
@dale42 : Your pull request has been merged in. Thank you so much for contributing!
